Repository GilDongMu/gildongmu, pull requests merged in 2024-04, with the labels that each got.

#175 전체글 데이터 및 이미지 수정
  components/card/index.tsx
  components/gnb/index.tsx
  components/mainCard/index.tsx
  components/travel/contents/cardGrid.tsx
  components/travel/contents/filterBtn.tsx
  components/travel/contents/pagingSetting.tsx
  lib/api/travel/index.ts
  public/images/Image_None.png
Labels: 리팩토링

#176 채팅 데이터 연결
  components/community/chatHeader/index.tsx
  components/community/chatUserList/index.tsx
  components/community/commuchat/index.tsx
  components/community/commulist/index.tsx
  components/community/myChat/index.tsx
  components/community/userChat/index.tsx
  lib/api/chat/index.ts
  package-lock.json
  package.json
  pages/community/[id]/index.tsx
Labels: 기능 추가

#177 서치바 검색 기능 추가
  components/header/searchbar.tsx
  components/travel/contents/cardGrid.tsx
  components/travel/contents/filter.tsx
  components/travel/contents/filterBtn.tsx
  lib/api/travel/index.ts
Labels: 기능 추가

#180 내여행 페이지 api 연동
  components/card/index.tsx
  components/carousel/travel/index.tsx
  components/header/mytravel/index.tsx
  components/modal/button.tsx
  components/modal/index.tsx
  components/modal/layout.tsx
  components/mytravel/card/Bookmark.tsx
  components/mytravel/card/Favor.tsx
  components/mytravel/card/index.tsx
  components/mytravel/modal/content/Bookmark.tsx
  components/mytravel/modal/content/Participating.tsx
  components/mytravel/modal/content/Recruiting.tsx
  components/mytravel/modal/content/Saving.tsx
  components/mytravel/modal/index.tsx
  components/mytravel/tabMenu/index.tsx
  components/ui/skeleton.tsx
  pages/mytravel/index.tsx
  public/images/Image_404.png
  public/images/Image_Chat.png
  public/images/Image_DefaultCard.png
  public/images/Image_LogIn.png
  public/images/Image_Travel.png
Labels: 버그 수정, 기능 추가, 리팩토링

#181 카드 오타 수정
  components/travel/contents/cardGrid.tsx
Labels: 리팩토링

#186 채팅 개발
  components/community/commuchat/index.tsx
  components/community/userChat/index.tsx
  pages/_app.tsx
  pages/community/[id]/index.tsx
Labels: 기능 추가

#187 로그인 필요 모달 ui 구현 및 기능 구현
  components/detail/article/title/index.tsx
  components/modal/button.tsx
  components/modal/index.tsx
  pages/_app.tsx
Labels: 디자인, 기능 추가

#192 상세페이지 댓글 기능(작성, 삭제, 수정) + 그에 필요한 모달 기능 및 디자인 구현
  components/detail/article/contents/comments/index.tsx
  components/detail/article/contents/comments/my/commentOfcomment/index.tsx
  components/detail/article/contents/comments/my/edit/index.tsx
  components/detail/article/contents/comments/my/index.tsx
  components/detail/article/contents/comments/my/secret/commentOfcomment/index.tsx
  components/detail/article/contents/comments/others/commentOfcomment/index.tsx
  components/detail/article/contents/comments/others/index.tsx
  components/detail/article/contents/comments/register/commentOfcomment/index.tsx
  components/detail/article/contents/comments/register/index.tsx
  components/detail/article/contents/comments/secret/index.tsx
  components/detail/article/contents/index.tsx
  components/detail/article/index.tsx
  components/detail/secretCheckbox/index.tsx
  components/modal/button.tsx
  components/modal/index.tsx
  lib/api/detail/index.ts
  lib/api/detail/type.ts
  pages/travel/[Id]/detail/index.tsx
  public/icons/cancel_white.svg
Labels: 기능 추가, 리팩토링

#195 상세페이지 버그수정, 불필요한 컴포넌트 제거, 댓글작성자 프로필사진 추가
  components/detail/article/contents/comments/index.tsx
  components/detail/article/contents/comments/my/commentOfcomment/index.tsx
  components/detail/article/contents/comments/my/edit/index.tsx
  components/detail/article/contents/comments/my/index.tsx
  components/detail/article/contents/comments/my/secret/commentOfcomment/index.tsx
  components/detail/article/contents/comments/my/secret/index.tsx
  components/detail/article/contents/comments/others/commentOfcomment/index.tsx
  components/detail/article/contents/comments/others/index.tsx
  components/modal/button.tsx
  components/modal/index.tsx
Labels: 버그 수정, 기능 추가, 리팩토링

#202 상세페이지 찜하기 /찜 취소 기능 구현
  components/detail/article/title/index.tsx
  pages/travel/[Id]/detail/index.tsx
Labels: 기능 추가

#200 상세 페이지 작성자 프로필 모달 api 연동
  components/modal/index.tsx
  components/mytravel/modal/index.tsx
  pages/_app.tsx
Labels: 버그 수정, 기능 추가

#203 로그인 페이지 디자인 & 기능 수정
  components/form/socialSignupForm/index.tsx
  pages/login/index.tsx
  pages/oauth2/login/index.tsx
  pages/oauth2/signup/index.tsx
Labels: 디자인, 로그인

#209 상세페이지 신청하기 기능
  components/detail/article/title/index.tsx
  components/detail/header/index.tsx
  lib/api/bookmarks/index.ts
  lib/api/detail/index.ts
  lib/api/detail/type.ts
Labels: 기능 추가, 리팩토링

#212 디자인 검수
  components/form/writeForm/index.tsx
  components/mytravel/card/Title.tsx
  components/mytravel/card/index.tsx
Labels: 디자인

#213 코드 점검
  components/card/index.tsx
  components/community/chatHeader/index.tsx
  components/form/mypageForm/index.tsx
  components/mainCard/index.tsx
  components/travel/contents/cardGrid.tsx
  components/travel/contents/pagingSetting.tsx
Labels: 리팩토링

#214 상세페이지 신청하기 기능 리팩토링
  components/community/commuchat/index.tsx
  components/detail/article/title/index.tsx
  components/modal/button.tsx
  components/modal/index.tsx
Labels: 기능 추가, 리팩토링

#221 전체글 리팩토링
  components/card/Skeleton/index.tsx
  components/card/index.tsx
  components/carousel/country/index.tsx
  components/carousel/travel/index.tsx
  components/community/chatHeader/index.tsx
  components/community/chatUserList/index.tsx
  components/community/commuchat/index.tsx
  components/community/commulist/index.tsx
  components/community/nicknameChange/index.tsx
  components/community/userChat/index.tsx
  components/detail/article/contents/comments/my/edit/index.tsx
  components/detail/article/contents/comments/my/index.tsx
  components/detail/article/contents/comments/others/index.tsx
  components/gnb/Hammenu/index.tsx
  components/gnb/index.tsx
  components/header/searchbar.tsx
  components/main/footer/index.tsx
  components/mainCard/Skeleton/index.tsx
  components/mainCard/index.tsx
  components/travel/contents/cardGrid.tsx
  components/travel/contents/filter.tsx
  components/travel/contents/paging.tsx
  components/travel/contents/pagingSetting.tsx
  next.config.js
  package-lock.json
  package.json
  pages/community/[id]/index.tsx
  pages/login/index.tsx
  pages/travel/index.tsx
  store/search.js
  vercel.json
Labels: 리팩토링
