Repository GilDongMu/gildongmu, pull requests merged in 2024-03, with the labels that each got.

#10 useToggle 훅 제작
  hooks/useToggle.tsx
Labels: 기능 추가

#34 회원가입 ui/ form 기능 구현
  components/form/input/DatePickerInput.tsx
  components/form/input/ImageUploadInput.tsx
  components/form/input/IntroTextarea.tsx
  components/form/input/RadioInput.tsx
  components/form/input/TagInput.tsx
  components/form/signupForm/index.tsx
  components/ui/calendar.tsx
  components/ui/input.tsx
  components/ui/label.tsx
  components/ui/popover.tsx
  components/ui/radio-group.tsx
  components/ui/textarea.tsx
  lib/utils/.gitkeep
  lib/utils/regexp.ts
  package-lock.json
  package.json
  pages/signup/index.tsx
  public/icons/calendar.png
  public/icons/cancel.svg
  public/icons/colorCalendar.png
  public/icons/defaultProfile.png
  public/icons/eye-off.png
  public/icons/eye-on.png
  public/icons/upload.png
  styles/globals.css
  tailwind.config.ts
Labels: 회원가입

#33 메인페이지 국내/해외 여행글 캐러셀 디자인 수정
  components/carousel/country/index.tsx
  components/carousel/custom/index.tsx
  public/icons/arrow_left.svg
  public/icons/arrow_right.svg
  public/icons/chevron_left.svg
  public/icons/chevron_right.svg
  styles/globals.css
Labels: 디자인, 리팩토링

#43 회원가입 input border 수정, 가입하기 버튼 hover
  components/form/input/DatePickerInput.tsx
  components/form/input/IntroTextarea.tsx
  components/form/input/TagInput.tsx
  components/form/signupForm/index.tsx
Labels: 디자인, 회원가입

#36 gnb hover 수정
  components/gnb/Dropdown/index.tsx
  components/gnb/Hammenu/index.tsx
  components/gnb/index.tsx
Labels: 디자인, 리팩토링

#45 버튼 공용 컴포넌트 구현
  components/ui/button.tsx
  styles/globals.css
  tailwind.config.ts
Labels: 공통 디자인

#42 전체글 페이지 헤더, 글쓰기 버튼 ui 구현
  components/button/writing.tsx
  components/header/index.tsx
  components/header/searchbar.tsx
  components/main/header/index.tsx
  pages/index.tsx
  public/icons/pencil.svg
Labels: 디자인, 리팩토링

#50 전체글 디자인
  components/card/index.tsx
  components/gnb/Dropdown/index.tsx
  components/gnb/Hammenu/index.tsx
  components/gnb/index.tsx
  components/travel/contents/cardGrid.tsx
  components/travel/contents/filter.tsx
  components/travel/contents/filterBtn.tsx
  components/travel/contents/gridNum.tsx
  components/travel/contents/paging.tsx
  components/travel/contents/pagingSetting.tsx
  pages/_app.tsx
  pages/travel/index.tsx
  public/icons/first_page.svg
  public/icons/keyboard_arrow_left.svg
  public/icons/keyboard_arrow_right.svg
  public/icons/last_page.svg
  public/icons/layout-grid.svg
  public/icons/list.svg
  store/.gitkeep
  store/gnb.js
  styles/globals.css
  tsconfig.json
Labels: 디자인, 기능 추가

#55 모달 버튼 ui 수정
  .prettierrc
  components/modal/alert/button.tsx
  components/ui/button.tsx
  pages/index.tsx
Labels: 디자인

#56 메인페이지 여행글 카드 영역 디자인 수정
  components/main/contents/travel.tsx
Labels: 디자인

#62 모달 버튼 ui hover 디자인 추가 및 수정
  components/ui/button.tsx
  pages/index.tsx
Labels: 디자인, 리팩토링

#61 axios 기본 세팅
  lib/api/axios.js
  tsconfig.json
Labels: 기능 추가

#66 캐러셀 화살표 이미지와 감싸는 태그의 property 수정
  components/carousel/country/index.tsx
  components/carousel/travel/index.tsx
Labels: 리팩토링

#63 전체글 페이지 제작
  components/card/index.tsx
  components/gnb/index.tsx
  components/travel/contents/cardGrid.tsx
  components/travel/contents/filter.tsx
  components/travel/contents/filterBtn.tsx
  components/travel/contents/paging.tsx
  package-lock.json
  package.json
  pages/travel/index.tsx
  tailwind.config.ts
Labels: 디자인

#65 카드 임시 데이터 넣어두기
  components/card/index.tsx
Labels: 기능 추가

#53 글쓰기 페이지 제작
  components/form/input/ContentInput.tsx
  components/form/input/CounterInput.tsx
  components/form/input/IntroTextarea.tsx
  components/form/input/MultipleImageUploadInput.tsx
  components/form/input/RadioInput.tsx
  components/form/input/RangeDatePickerInput.tsx
  components/form/input/TagInput.tsx
  components/form/signupForm/index.tsx
  components/form/writeForm/index.tsx
  components/modal/alert/button.tsx
  components/modal/alert/index.tsx
  pages/signup/index.tsx
  pages/write/index.tsx
  public/icons/imagePlus.svg
Labels: 디자인

#73 카드 스타일 빠진거 수정
  components/card/index.tsx
Labels: 디자인, 리팩토링

#79 로그인 눈 토글 구현
  pages/login/index.tsx
Labels: 로그인

#80 사용자 프로필, 신청하기, 취소하기 모달 구현
  components/form/signupForm/index.tsx
  components/form/writeForm/index.tsx
  components/modal/alert/index.tsx
  components/modal/alert/layout.tsx
  components/modal/button.tsx
  components/modal/index.tsx
  components/modal/layout.tsx
Labels: 디자인

#82 로그인 추가 & 회원가입 링크 넣기
  pages/login/index.tsx
Labels: 로그인

#83 로그인 에러 처리
  pages/login/index.tsx
Labels: 기능 추가, 로그인

#85 gnb색상 변경 수정
  components/gnb/Hammenu/index.tsx
  components/gnb/index.tsx
  pages/_app.tsx
Labels: 디자인, 리팩토링

#87 dropdown 수정
  components/dropdown/index.tsx
  components/gnb/Dropdown/index.tsx
  components/gnb/index.tsx
  components/travel/contents/pagingSetting.tsx
  package-lock.json
  package.json
Labels: 기능 추가, 리팩토링

#90 상세페이지 pc 사이즈 디자인 구현
  components/detail/article/contents/comments/index.tsx
  components/detail/article/contents/comments/my/commentOfcomment/index.tsx
  components/detail/article/contents/comments/my/index.tsx
  components/detail/article/contents/comments/my/secret/commentOfcomment/index.tsx
  components/detail/article/contents/comments/my/secret/index.tsx
  components/detail/article/contents/comments/others/commentOfcomment/index.tsx
  components/detail/article/contents/comments/others/index.tsx
  components/detail/article/contents/comments/register/commentOfcomment/index.tsx
  components/detail/article/contents/comments/register/index.tsx
  components/detail/article/contents/comments/secret/commentOfcomment/index.tsx
  components/detail/article/contents/comments/secret/index.tsx
  components/detail/article/contents/destination/descriptionImages/index.tsx
  components/detail/article/contents/destination/index.tsx
  components/detail/article/contents/index.tsx
  components/detail/article/contents/recruitment/index.tsx
  components/detail/article/contents/sort/index.tsx
  components/detail/article/index.tsx
  components/detail/article/title/index.tsx
  components/detail/header/index.tsx
  components/detail/secretCheckbox/index.tsx
  components/detail/tag/index.tsx
  components/ui/checkbox.tsx
  next.config.js
  package-lock.json
  package.json
  pages/travel/[Id]/detail/index.tsx
  public/icons/chevron_left.svg
  public/icons/chevron_left_sky.svg
  public/icons/chevron_right_sky.svg
  public/icons/frame.svg
  public/icons/location_red.svg
  public/icons/lock.svg
  public/icons/more_vertical.svg
  public/icons/profile.svg
  public/icons/rocket.svg
  public/images/stroke_blue.svg
  styles/globals.css
  tailwind.config.ts
Labels: 디자인, 기능 추가, 리팩토링

#95 전체글 필터 준비
  components/dropdown/index.tsx
  components/gnb/index.tsx
  components/travel/contents/cardGrid.tsx
  components/travel/contents/filter.tsx
  components/travel/contents/filterBtn.tsx
  components/travel/contents/pagingSetting.tsx
  store/cardfilter.js
  store/choiceSort.js
Labels: 기능 추가

#96 상세보기 페이지 타이틀
  components/DetailTitle.tsx
  components/modal/button.tsx
  components/modal/index.tsx
  public/icons/heart-empty.svg
  public/icons/heart-notEmpty.svg
  public/icons/profileArrow.svg
  public/icons/writeDelete.svg
  public/icons/writeEdit.svg
  styles/globals.css
Labels: 디자인

#98 회원가입 성공 시 로그인 페이지 이동
  components/form/signupForm/index.tsx
Labels: 회원가입

#94 로그인 페이지 오류 수정
  pages/login/index.tsx
Labels: 버그 수정, 로그인

#100 footer 제작
  components/main/footer/index.tsx
  public/icons/symbol.svg
Labels: 디자인

#102 구글맵 구현
  components/carousel/country/index.tsx
  components/detail/article/contents/destination/index.tsx
  components/form/writeForm/index.tsx
  components/googlemap/index.tsx
  package-lock.json
  package.json
  public/icons/chevron-left.svg
  public/icons/chevron-right.svg
Labels: 디자인, 기능 추가

#106 메인페이지 디자인 수정
  components/carousel/country/index.tsx
  components/carousel/travel/index.tsx
  components/header/searchbar.tsx
  components/main/header/searchbar.tsx
Labels: 디자인

#107 상세페이지 댓글,답글 수정,삭제하기 기능을 포함한 드롭다운 구현
  components/detail/article/contents/comments/my/commentOfcomment/index.tsx
  components/detail/article/contents/comments/my/index.tsx
  components/detail/article/contents/comments/my/secret/commentOfcomment/index.tsx
  components/detail/article/contents/comments/my/secret/index.tsx
  components/dropdown/index.tsx
Labels: 디자인, 리팩토링

#109 gnb 수정
  components/dropdown/index.tsx
  components/gnb/index.tsx
  components/travel/contents/pagingSetting.tsx
Labels: 디자인, 리팩토링

#111 상세 페이지 타이틀 분기 모바일 반응형 디자인 추가
  components/detail/title/DetailTitle.tsx
  pages/travel/[Id]/detail/index.tsx
Labels: 디자인

#117 상세페이지 디자인 수정 및 그에 필요한 기능 구현
  components/detail/article/contents/comments/index.tsx
  components/detail/article/contents/destination/index.tsx
  components/detail/article/contents/index.tsx
  components/detail/article/contents/recruitment/index.tsx
  components/detail/article/contents/sort/index.tsx
  package-lock.json
  package.json
Labels: 디자인, 기능 추가, 리팩토링

#115 모달 수정
  components/modal/layout.tsx
Labels: 디자인, 리팩토링

#119 소셜 로그인 추가
  pages/login/index.tsx
Labels: 인증, 로그인

#123 gnb 수정
  components/gnb/index.tsx
  pages/_app.tsx
Labels: 디자인, 리팩토링

#121 상세페이지 반응형 디자인 구현
  components/detail/article/contents/comments/index.tsx
  components/detail/article/contents/comments/my/commentOfcomment/index.tsx
  components/detail/article/contents/comments/my/index.tsx
  components/detail/article/contents/comments/my/secret/commentOfcomment/index.tsx
  components/detail/article/contents/comments/my/secret/index.tsx
  components/detail/article/contents/comments/others/commentOfcomment/index.tsx
  components/detail/article/contents/comments/others/index.tsx
  components/detail/article/contents/comments/register/commentOfcomment/index.tsx
  components/detail/article/contents/comments/register/index.tsx
  components/detail/article/contents/comments/secret/commentOfcomment/index.tsx
  components/detail/article/contents/comments/secret/index.tsx
  components/detail/article/contents/destination/descriptionImages/index.tsx
  components/detail/article/contents/destination/index.tsx
  components/detail/article/contents/index.tsx
  components/detail/article/contents/recruitment/index.tsx
  components/detail/article/contents/sort/index.tsx
  components/detail/article/index.tsx
  components/detail/article/title/index.tsx
  components/detail/header/index.tsx
  components/detail/title/DetailTitle.tsx
  pages/travel/[Id]/detail/index.tsx
Labels: 디자인

#124 전체글 필터 / 카드 수정
  components/card/index.tsx
  components/travel/contents/.cardGrid.tsx.swp
  components/travel/contents/cardGrid.tsx
  components/travel/contents/filter.tsx
  components/travel/contents/filterBtn.tsx
  components/travel/contents/gridNum.tsx
  components/travel/contents/pagingSetting.tsx
  lib/api/axios.js
Labels: 디자인, 기능 추가, 리팩토링

#128 리액트 쿼리 세팅
  pages/_app.tsx
Labels: 기능 추가

#131 쿠키 임시 저장
  pages/login/index.tsx
Labels: 기능 추가

#150 내보내기, 수정완료, 내여행페이지 모달 ui 구현
  components/carousel/country/index.tsx
  components/carousel/travel/index.tsx
  components/modal/button.tsx
  components/modal/index.tsx
  components/mytravel/Card/Favor.tsx
  components/mytravel/Card/FlipButton.tsx
  components/mytravel/Card/RecruitmentStatus.tsx
  components/mytravel/Card/Title.tsx
  components/mytravel/Card/index.tsx
  components/mytravel/TabMenu/index.tsx
  components/mytravel/card/index.tsx
  components/mytravel/modal/Chip.tsx
  components/mytravel/modal/content/Participating.tsx
  components/mytravel/modal/content/Recruiting.tsx
  components/mytravel/modal/content/Saving.tsx
  components/mytravel/modal/index.tsx
  components/mytravel/tabMenu/index.tsx
  pages/mytravel/index.tsx
  public/icons/arrow_right_sky.svg
  public/icons/chevron-left-gray.png
  public/icons/chevron-right-blue.png
  public/icons/chevron-right-gray.png
  public/icons/crown.svg
Labels: 디자인

#152 상세페이지/eonpain/146
  components/detail/article/contents/destination/descriptionImages/index.tsx
  components/detail/article/contents/destination/index.tsx
  components/detail/article/contents/index.tsx
  components/detail/article/contents/recruitment/index.tsx
  components/detail/article/index.tsx
  components/detail/article/title/index.tsx
  lib/api/detail/index.ts
  lib/api/detail/type.ts
  pages/travel/[Id]/detail/index.tsx
Labels: 기능 추가

#153 채팅방 ui 제작 / 전체글 카드 수정 및 찜기능 추가
  components/card/index.tsx
  components/community/chatCome/index.tsx
  components/community/chatDate/index.tsx
  components/community/chatHeader/index.tsx
  components/community/chatUserList/index.tsx
  components/community/commuchat/index.tsx
  components/community/commulist/index.tsx
  components/community/myChat/index.tsx
  components/community/userChat/index.tsx
  components/gnb/Hammenu/index.tsx
  components/gnb/index.tsx
  lib/api/bookmarks/index.ts
  lib/api/chat/index.ts
  lib/api/userMe/index.ts
  pages/community/[id]/index.tsx
  pages/community/index.tsx
  public/images/button_off.svg
  public/images/button_on.svg
  public/images/chat.svg
  store/cardfilter.js
  store/loginState.js
Labels: 디자인, 기능 추가

#157 상세페이지 이미지 클래스 속성 수정, 불필요한 드롭다운 삭제
  components/detail/article/contents/comments/register/commentOfcomment/index.tsx
  components/detail/article/contents/destination/descriptionImages/index.tsx
Labels: 리팩토링

#159 전체글 / 소통공간 / gnb 디자인 지적당한 부분 수정
  components/card/index.tsx
  components/community/commulist/index.tsx
  components/community/header/index.tsx
  components/header/index.tsx
  components/mainCard/index.tsx
  components/travel/contents/filter.tsx
  components/travel/contents/filterBtn.tsx
  hooks/isMobile.ts
  pages/travel/index.tsx
  styles/globals.css
Labels: 디자인, 리팩토링

#162 소통공간 데이터 연결 준비
  components/community/commuchat/index.tsx
  components/community/commulist/index.tsx
  components/dropdown/index.tsx
  components/gnb/index.tsx
  hooks/useCookie.tsx
  lib/api/chat/index.ts
  package-lock.json
  package.json
  pages/community/[id]/index.tsx
  pages/login/index.tsx
Labels: 기능 추가, 리팩토링

#163 상세페이지 디자인 수정
  components/detail/article/contents/comments/index.tsx
  components/detail/article/contents/comments/my/commentOfcomment/index.tsx
  components/detail/article/contents/comments/my/index.tsx
  components/detail/article/contents/comments/my/secret/commentOfcomment/index.tsx
  components/detail/article/contents/comments/my/secret/index.tsx
  components/detail/article/contents/destination/descriptionImages/index.tsx
  components/detail/article/contents/destination/index.tsx
  components/detail/article/contents/recruitment/index.tsx
  components/detail/article/contents/sort/index.tsx
  components/detail/article/index.tsx
  components/detail/header/index.tsx
Labels: 디자인, 리팩토링

#164 소셜 로그인 완료
  components/form/socialSignupForm/index.tsx
  pages/login/index.tsx
  pages/oauth2/login/index.tsx
  pages/oauth2/signup/index.tsx
Labels: 기능 추가, 로그인

#170 마이페이지 데이터 연동
  components/form/input/ImageUploadInput.tsx
  components/form/input/MultipleImageUploadInput.tsx
  components/form/mypageForm/index.tsx
  components/gnb/Hammenu/index.tsx
  components/modal/button.tsx
  components/modal/index.tsx
  components/ui/radio-group.tsx
  next.config.js
  pages/mypage/index.tsx
  public/icons/checkbox.svg
Labels: 기능 추가
